//
//  Food.swift
//  Coma Certo
//
//  Created by Eduardo Soares on 11/08/2018.
//  Copyright © 2018 Eduardo Soares. All rights reserved.
//

import Foundation
struct Food {
    static let allFoods = [
        Food("Água de coco verde"),
        Food("Café com açúcar"),
        Food("Café sem açúcar"),
        Food("Caldo de cana"),
        Food("Suco de abacaxi natural"),
        Food("Suco de acerola natural"),
        Food("Suco de maçã natural"),
        Food("Suco de manga natural"),
        Food("Suco de melão natural"),
        Food("Suco de milho verde natural"),
        Food("Suco de morango natural"),
        Food("Suco de pêssego natural"),
        Food("Suco de tomate frescoAguardente"),
        Food("Cerveja"),
        Food("Cerveja light"),
        Food("Champanhe"),
        Food("Chope"),
        Food("Uísque"),
        Food("Vinho branco doce"),
        Food("Vinho branco seco"),
        Food("Vinho Rosé"),
        Food("Vinho tinto seco"),
        Food("VodkaCoca-Cola"),
        Food("Coca-Cola Light"),
        Food("Fanta"),
        Food("Fanta Diet"),
        Food("Gatorate – todos os sabores"),
        Food("Guaraná"),
        Food("Guaraná diet"),
        Food("Sport Drink limão"),
        Food("Sprite"),
        Food("Sprite diet limãoAlcatra assada"),
        Food("Alcatra frita"),
        Food("Almôndega caseira de carne"),
        Food("Almôndega de frango"),
        Food("Almôndega de peru"),
        Food("Antecoxa de frango assada"),
        Food("Baby beef"),
        Food("Bacon fatiado"),
        Food("Bacon frito"),
        Food("Bisteca de porco"),
        Food("Costeleta de porco"),
        Food("Coxa de frango"),
        Food("Coxa de frango assada c/pele"),
        Food("Coxa de frango assada s/pele"),
        Food("Coxa de frango cozida"),
        Food("Cupim"),
        Food("Fígado de boi frito"),
        Food("Fígado de galinha"),
        Food("Filé de frango"),
        Food("Filé mignon"),
        Food("Hamburger bovina"),
        Food("Hamburger calabresa"),
        Food("Hamburger de chester"),
        Food("Hamburger de frango"),
        Food("Lagarto de boi assado"),
        Food("Leitão"),
        Food("Língua de boi cozida"),
        Food("Lombo assado"),
        Food("Maminha"),
        Food("Miolo de coxão mole"),
        Food("Moela de galinha"),
        Food("Músculo cozido"),
        Food("Patinho de boi assado"),
        Food("Peito de frango s/pele"),
        Food("Pernil de porco assado"),
        Food("Perú"),
        Food("Picanha"),
        Food("Rã"),
        Food("Rabo de porco salgado"),
        Food("Rosbife"),
        Food("TenderApresuntado"),
        Food("Blanquet de peru"),
        Food("Copa fatiada maturada"),
        Food("Lingüiça calabresa"),
        Food("Lingüiça de frango"),
        Food("Lingüiça de peru defumada"),
        Food("Lingüiça toscana"),
        Food("Lombo canadense"),
        Food("Lombo defumado"),
        Food("Morcela"),
        Food("Mortadela"),
        Food("Mortadela de frango"),
        Food("Paio"),
        Food("Peito de peru defumado"),
        Food("Presunto cozido"),
        Food("Presunto cru"),
        Food("Salame italiano"),
        Food("Salaminho"),
        Food("Salsinha"),
        Food("Salsicha light de chester"),
        Food("Salsicha Hot Dog"),
        Food("SalsichãoAnchova cozida"),
        Food("Anchova à milanesa"),
        Food("Atum cru"),
        Food("Bacalhau cozido"),
        Food("Cação cozido"),
        Food("Camarão cozido"),
        Food("Camarão frito"),
        Food("Casquinha de Caranguejo"),
        Food("Casquinha de Siri"),
        Food("Caviar"),
        Food("Dourado"),
        Food("Haddock cozido"),
        Food("Kani-Kama"),
        Food("Lagosta cozida s/ molho"),
        Food("Linguado assado ou grelhado"),
        Food("Lula cozida"),
        Food("Lula frita empanada"),
        Food("Mariscos cozidos"),
        Food("Mexilhão cozido"),
        Food("Namorado cozido"),
        Food("Ostras"),
        Food("Ovas de peixe cruas"),
        Food("Pescada cozida"),
        Food("Pintado grelhado"),
        Food("Polvo cru"),
        Food("Robalo"),
        Food("Salmão assado ou grelhado"),
        Food("Salmão cru"),
        Food("Sardinha grelhada"),
        Food("Sardinha em óleo comestível"),
        Food("Sardinha em conserva com azeite"),
        Food("Tainha Cozida"),
        Food("Truta assada ou grelhadaÁgua e sal"),
        Food("Biscoito de manteiga"),
        Food("Biscoito integral de trigo"),
        Food("Champanhe"),
        Food("Cream Cracker"),
        Food("Leite"),
        Food("Maisena"),
        Food("Maria"),
        Food("Palitinhos salgados"),
        Food("Passatempo alpino"),
        Food("Recheado chocolate"),
        Food("Recheado morango"),
        Food("Salclic aperitivo"),
        Food("Waffer chocolateCaramelo ao leite"),
        Food("Goma média"),
        Food("Halls"),
        Food("Halls diet"),
        Food("JujubaAna Maria Pullman"),
        Food("Bolo de cenoura caseiro"),
        Food("Bolo de cenoura com cobertura de chocolate"),
        Food("Bolo de chocolate"),
        Food("Bolo de fubá caseiro"),
        Food("Bolo de Laranja"),
        Food("Bolo pão-de-ló"),
        Food("Bolo de cocoAerado ao leite"),
        Food("Alfajor chocolate"),
        Food("Alpino Bombom chocolate ao leite"),
        Food("Chocolate meio-amargo"),
        Food("Ao leite"),
        Food("Baton"),
        Food("Bis"),
        Food("Chocolate em pó solúvel"),
        Food("Diamante Negro"),
        Food("Diplomata"),
        Food("Chocolate Branco"),
        Food("Ouro Branco"),
        Food("Sulflair"),
        Food("TrufasAmendoim c/ chocolate"),
        Food("Apfelstrudell"),
        Food("Arroz-doce"),
        Food("Baba-de-moça"),
        Food("Banana Caramelada"),
        Food("Bananada"),
        Food("Banana passa"),
        Food("Bomba de chocolate"),
        Food("Bomba de chocolate c/&nbsp;cobertura de chocolate"),
        Food("Bombocado"),
        Food("Brigadeiro"),
        Food("Cajuzinho"),
        Food("Calda de caramelo"),
        Food("Calda de chocolate com leite"),
        Food("Canjica"),
        Food("Chantibon"),
        Food("Claybon Amendocrem"),
        Food("Cobertura de caramelo"),
        Food("Cobertura de cereja"),
        Food("Cobertura de chocolate"),
        Food("Cobertura de marshmellow"),
        Food("Cocada Branca"),
        Food("Creme de amendoim"),
        Food("Creme de marshmellow"),
        Food("Doce de Banana mole"),
        Food("Doce de leite"),
        Food("Folheado com creme"),
        Food("Framboesa em calda"),
        Food("Geléia de goiaba"),
        Food("Geléia de morango"),
        Food("Geléia de mocotó"),
        Food("Marmelada"),
        Food("Marrom glacê"),
        Food("Mel com própolis"),
        Food("Mel de abelhas"),
        Food("Mousse de chocolate"),
        Food("Paçoca"),
        Food("Pamonha"),
        Food("Papo-de-anjo"),
        Food("Pastel de Santa Clara"),
        Food("Pavê"),
        Food("Pé-de-moleque"),
        Food("Pêssego em calda"),
        Food("Pudim de arroz caseiro"),
        Food("Quindim caseiro"),
        Food("Rabanada"),
        Food("Rapadura"),
        Food("Sonho"),
        Food("Suspiro pequenoAbacaxi"),
        Food("Cereja"),
        Food("Framboesa"),
        Food("Limão"),
        Food("Morango"),
        Food("UvaAo leite coco"),
        Food("Ao leite morango"),
        Food("Banana Split"),
        Food("Colegial"),
        Food("Milk-Shake Baunilha"),
        Food("Milk-Shake Chocolate"),
        Food("Sorvete de massa chocolate creme morango e coco"),
        Food("Sorvete de massa de limão"),
        Food("SundaeAçúcar branco refinado"),
        Food("Açúcar Mascavo"),
        Food("Alcaparra sem azeitona"),
        Food("Alho"),
        Food("Caldo de carne"),
        Food("Caldo de galinha"),
        Food("Cebola crua"),
        Food("Cheiro verde"),
        Food("Curry"),
        Food("Erva-doce"),
        Food("Extrato de tomate"),
        Food("Ketchup"),
        Food("Leite de coco"),
        Food("Molho de pimenta vermelha"),
        Food("Molho Inglês"),
        Food("Mostarda"),
        Food("Páprica"),
        Food("Pimenta-do-reino"),
        Food("Sal branco refinado"),
        Food("Shoyu"),
        Food("VinagreBranco"),
        Food("Chutney de manga"),
        Food("Maionese"),
        Food("Molho agridoce"),
        Food("Molho de iogurte"),
        Food("Molho roquefort"),
        Food("Molho rose"),
        Food("Molho de tomate caseiro"),
        Food("Molho tártaroAzeite-de-dendê"),
        Food("Azeite de oliva"),
        Food("Banha de galinha"),
        Food("Banha de porco industrializada"),
        Food("Gordura vegetal hidrogenada"),
        Food("Manteiga com sal"),
        Food("Margarina"),
        Food("Óleo de algodão"),
        Food("Óleo de amendoim"),
        Food("Óleo de canola"),
        Food("Óleo de fígado de bacalhau"),
        Food("Óleo de gergelim"),
        Food("Óleo de girassol"),
        Food("Óleo de milho"),
        Food("Óleo de peixe"),
        Food("Óleo de sojaAbacate"),
        Food("Abacaxi"),
        Food("Acerola"),
        Food("Banana-da-terra"),
        Food("Banana-maçã"),
        Food("Banana-nanica"),
        Food("Banana-prata crua"),
        Food("Caju"),
        Food("Cana-de-açúcar"),
        Food("Caqui chocolate"),
        Food("Castanha de caju picada"),
        Food("Cereja"),
        Food("Coco ralado fresco"),
        Food("Figo maduro"),
        Food("Framboesa"),
        Food("Goiaba vermelha"),
        Food("Graviola"),
        Food("Guaraná"),
        Food("Kiwi"),
        Food("Laranja"),
        Food("Limão"),
        Food("Maçã verde"),
        Food("Maçã vermelha"),
        Food("Mamão maduro"),
        Food("Manga"),
        Food("Maracujá comum (polpa)"),
        Food("Melancia"),
        Food("Melão"),
        Food("Morango"),
        Food("Nozes"),
        Food("Pêra crua"),
        Food("Pêra seca"),
        Food("Pêssego"),
        Food("Tangerina"),
        Food("Uva branca nacional"),
        Food("Uva passaAgite morango Danone"),
        Food("Coalhada"),
        Food("Batavo c/ mel"),
        Food("Corpus Diet morango"),
        Food("Danette"),
        Food("Danoninho morango"),
        Food("Dan’up"),
        Food("Iogurte batido com açúcar e mel"),
        Food("Iogurte desnatado light Batavo"),
        Food("Iogurte natural batido Vigor"),
        Food("Iogurte natural batido light Vigor"),
        Food("Iogurte natural Paulista"),
        Food("Iogurte natural light Paulista"),
        Food("Neston c/ cereal e frutas"),
        Food("Parmalat natural desnatado"),
        Food("Shake morango NestléAchocolatado Leco"),
        Food("Chocolate pronto Glória"),
        Food("Creme de leite"),
        Food("Leite com chocolate"),
        Food("Leite condensado"),
        Food("Leite de búfala"),
        Food("Leite de cabra"),
        Food("Leite de soja"),
        Food("Leite em pó desnatado"),
        Food("Leite em pó integral"),
        Food("Leite integral"),
        Food("Leite longa vida c/ ferro"),
        Food("Leite semidesnatadoBrie"),
        Food("Camembert"),
        Food("Catupiry"),
        Food("Cheddar americano"),
        Food("Cottage Lacreme"),
        Food("Cream cheese light Danúbio"),
        Food("Cream cheese tradicional Alouette"),
        Food("Edam"),
        Food("Ementhal"),
        Food("Estepe"),
        Food("Gorgonzola"),
        Food("Gouda Luna"),
        Food("Gruyère francês"),
        Food("Mussarela"),
        Food("Palmira"),
        Food("Parmesão"),
        Food("Pecorino"),
        Food("Petit-Suisse"),
        Food("Polenguinho"),
        Food("Prato"),
        Food("Provolone"),
        Food("Queijo-de-minas"),
        Food("Queijo-de-minas semicurado"),
        Food("Queijo-do-reino"),
        Food("Ricota de leite integral"),
        Food("Requeijão cremoso Nestlé"),
        Food("Requeijão cremoso light Nestlé"),
        Food("Roquefort"),
        Food("Suíço"),
        Food("Tofú (queijo de soja)Omelete"),
        Food("Ovo de codorna"),
        Food("Ovo de galinha cozido"),
        Food("Ovo de galinha frito"),
        Food("Ovo mexidoAbóbora"),
        Food("Agrião"),
        Food("Aipim frito"),
        Food("Alface"),
        Food("Amendoim"),
        Food("Arroz branco cozido"),
        Food("Arroz integral cozido"),
        Food("Aspargo cozido"),
        Food("Azeitona preta"),
        Food("Azeitona verde"),
        Food("Batata-doce assada"),
        Food("Batata-doce frita"),
        Food("Batata palha frita"),
        Food("Berinjela"),
        Food("Beterraba"),
        Food("Brócolis"),
        Food("Cebola"),
        Food("Cebola cozida"),
        Food("Cenoura"),
        Food("Cenoura cozida"),
        Food("Couve-flor cozida"),
        Food("Ervilha em conserva"),
        Food("Escarola"),
        Food("Espinafre"),
        Food("Feijão-branco cozido"),
        Food("Feijão cozido e desidratado"),
        Food("Feijão-preto cozido"),
        Food("Mandioca frita"),
        Food("Palmito cru"),
        Food("Palmito em conserva"),
        Food("Pepino cru com casca"),
        Food("Pepino cru sem casca"),
        Food("Repolho"),
        Food("Repolho cozido"),
        Food("Tomate cozido"),
        Food("Tomate maduro"),
        Food("Vagem cozidaBaguete"),
        Food("Baguete com gergelim"),
        Food("Bisnaguinha"),
        Food("Brioche"),
        Food("Broa de milho"),
        Food("Croissant"),
        Food("Panetone"),
        Food("Pão de batata-inglesa"),
        Food("Pão de cará"),
        Food("Pão de centeio integral"),
        Food("Pão francês"),
        Food("Pão de fôrma tradicional"),
        Food("Pão de hambúrguer"),
        Food("Pão de hot-dog"),
        Food("Pão de mel c/ cobertura de chocolate"),
        Food("Pão de queijo"),
        Food("Pão integral de trigo"),
        Food("Pão sírio integralCanelone de presunto e queijo à bolonhesa"),
        Food("Capelete de carne"),
        Food("Capelete de frango"),
        Food("Espaguete comum cozido"),
        Food("Espaguete ao sugo"),
        Food("Lasanha"),
        Food("Macarrão à carbonara"),
        Food("Macarrão integral cozido"),
        Food("Macarrão com molho de tomate e queijo"),
        Food("Macarrão cozido"),
        Food("Macarronada"),
        Food("Nhoque s/ molho"),
        Food("Pizza alho e óleo"),
        Food("Pizza de calabresa"),
        Food("Pizza de catupiry com tomate"),
        Food("Pizza de champignon c/ mussarela"),
        Food("Pizza de escarola c/ mussarela"),
        Food("Pizza de frango com catupiry"),
        Food("Pizza de mussarela"),
        Food("Pizza margherita"),
        Food("Pizza portuguesa"),
        Food("Pizza quatro queijosAveia em flocos"),
        Food("Corn Flakes"),
        Food("Farinha de amendoim"),
        Food("Farinha de arroz"),
        Food("Farinha de aveia-crua"),
        Food("Farinha de batata-doce"),
        Food("Farinha de batata-inglesa"),
        Food("Farinha de fubá de milho"),
        Food("Farinha de mandioca"),
        Food("Farinha de milho integral"),
        Food("Farinha de rosca"),
        Food("Farinha de trigo"),
        Food("Granola com castanhas"),
        Food("Grão de aveia cru"),
        Food("Germe de trigo"),
        Food("Maisena"),
        Food("Malte em póArroz com feijão"),
        Food("Arroz-de-carreteiro"),
        Food("Bife à parmegiana"),
        Food("Carne de panela"),
        Food("Creme de milho c/ leite e maisena"),
        Food("Empadão de frango"),
        Food("Estrogonofe"),
        Food("Farofa"),
        Food("Feijoada"),
        Food("Frango xadrez"),
        Food("Leitão a pururuca"),
        Food("Moqueca de peixe"),
        Food("Panqueca"),
        Food("Pimentão assado com carne"),
        Food("Rabada"),
        Food("Ratatoille"),
        Food("Risoto caseiro"),
        Food("Salada de batata"),
        Food("Sashimi c/ atum namorado, linguado e nabo"),
        Food("Tabule"),
        Food("Torta de camarão"),
        Food("VatapáBeirute"),
        Food("Cachorro-quente com maionese e molho vinagrete"),
        Food("Cachorro-quente com ketchup"),
        Food("Cachorro-quente com mostarda"),
        Food("Cachorro-quente com ketchup e mostarda"),
        Food("Cheeseburguer"),
        Food("Cheese salada com maionese"),
        Food("Hambúrguer"),
        Food("Misto quente"),
        Food("Sanduíche de lingüiça"),
        Food("Sanduíche de peito de peru"),
        Food("Sanduíche de queijo quente"),
        Food("Sanduíche de salada de atum")
    ]
    let name:String
    init(_ name:String) {
        self.name = name
    }
}
